topic:
  tracab:
    name: tracab-01-raw
    replication-factor: 2
    partitions: 3

spring:
  kafka:
    bootstrap-servers:
      - ${DATAPLATFORM_IP}:9092
      - ${DATAPLATFORM_IP}:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 1
      buffer-memory: 33554432
      properties:
        auto.register.schemas: true
        use.latest.version: true
    properties:
      schema.registry.url: "http://${DATAPLATFORM_IP}:8081"
