topic:
  tracab-01:
    name: tracab-01-raw
    replication-factor: 2
    partitions: 3
  tracab-02:
    name: tracab-02
    replication-factor: 2
    partitions: 3

spring:
  application:
    name: "spring-tracab-worker01"

  kafka:
    bootstrap-servers:
      - ${DATAPLATFORM_IP}:9092
      - ${DATAPLATFORM_IP}:9093
    streams:
      application-id: ${spring.application.name}
      client-id: ${spring.application.name}-stream
      properties:
        default.key.serde: Serdes.String().getClass().getName()
        default.value.serde: GenericAvroSerde.class
        # This is the default: log, fail and stop processing records (stop stream)
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler
    properties:
      bootstrap.servers: ${spring.kafka.bootstrap-servers}
      schema.registry.url: "http://${DATAPLATFORM_IP}:8081"
    # At application startup a missing topic on the broker will not fail the
    # application startup
    listener:
      missing-topics-fatal: false
